import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/Navbar";
import TrpcProvider from "@/components/global/TrpcProvider";
import SessionAuth from "@/components/global/SessionAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full ">
      <SessionAuth>
        <body
          className={cn(
            inter.className,
            "min-h-screen relative flex flex-col "
          )}
        >
          <div className="absolute top-0 right-0   z-[-2] min-h-screen h-full w-screen bg-white bg-[radial-gradient(100%_50%_at_50%_0%,rgba(0,163,255,0.13)_0,rgba(0,163,255,0)_50%,rgba(0,163,255,0)_100%)]"></div>
          <main className="relative w-full h-full">
            <TrpcProvider>
              <Navbar />
              {children}
            </TrpcProvider>
          </main>
        </body>
      </SessionAuth>
    </html>
  );
}
